### ISSUE TITLE
你好，请问上报的接口中deviceInfo和record字段是有什么作用，我尝试的时候都是空对象和空数组

### ISSUE THREAD

**Issue by C-somnus** [clouDr-f2e/monitor#38]
你好，请问上报的接口中deviceInfo和record字段是有什么作用，我尝试的时候都是空对象和空数组

**Comment by cjinhuo** [comment]
> 你好，请问上报的接口中deviceInfo和record字段是有什么作用，我尝试的时候都是空对象和空数组

deviceInfo是为了收集设备信息，比如当前网络类型、分辨率等等目前只有在小程序那块收集，record是收集页面录制的数据，当前没有对外开放SDK

**Comment by C-somnus** [comment]
> > 你好，请问上报的接口中deviceInfo和record字段是有什么作用，我尝试的时候都是空对象和空数组
> 
> deviceInfo是为了收集设备信息，比如当前网络类型、分辨率等等目前只有在小程序那块收集，record是收集页面录制的数据，当前没有对外开放SDK

感谢答复，后续有开放计划吗。另外在问一下按钮点击事件记录UI.Click是不是没有对外开放

**Comment by cjinhuo** [comment]
> > > 你好，请问上报的接口中deviceInfo和record字段是有什么作用，我尝试的时候都是空对象和空数组
> > 
> > 
> > deviceInfo是为了收集设备信息，比如当前网络类型、分辨率等等目前只有在小程序那块收集，record是收集页面录制的数据，当前没有对外开放SDK
> 
> 感谢答复，后续有开放计划吗。另外在问一下按钮点击事件记录UI.Click是不是没有对外开放

UI.Click目前是有记录的，开源计划：目前正在优化前后端代码 ，后续会在 https://github.com/mitojs  这里面持续迭代的

**Comment by C-somnus** [comment]
> > > > 你好，请问上报的接口中deviceInfo和record字段是有什么作用，我尝试的时候都是空对象和空数组
> > > 
> > > 
> > > deviceInfo是为了收集设备信息，比如当前网络类型、分辨率等等目前只有在小程序那块收集，record是收集页面录制的数据，当前没有对外开放SDK
> > 
> > 
> > 感谢答复，后续有开放计划吗。另外在问一下按钮点击事件记录UI.Click是不是没有对外开放
> 
> UI.Click目前是有记录的，开源计划：目前正在优化前后端代码 ，后续会在 https://github.com/mitojs 这里面持续迭代的

UI.Click需要做什么配置吗，我在react demo里加了个点击事件出现异常的时候，控制台并没有打印出来。
![demo-console](https://user-images.githubusercontent.com/17853356/129701848-1093a72a-040b-4f3c-a913-3f2b430ad338.png)

**Comment by cjinhuo** [comment]
> > > > > 你好，请问上报的接口中deviceInfo和record字段是有什么作用，我尝试的时候都是空对象和空数组
> > > > 
> > > > 
> > > > deviceInfo是为了收集设备信息，比如当前网络类型、分辨率等等目前只有在小程序那块收集，record是收集页面录制的数据，当前没有对外开放SDK
> > > 
> > > 
> > > 感谢答复，后续有开放计划吗。另外在问一下按钮点击事件记录UI.Click是不是没有对外开放
> > 
> > 
> > UI.Click目前是有记录的，开源计划：目前正在优化前后端代码 ，后续会在 https://github.com/mitojs 这里面持续迭代的
> 
> UI.Click需要做什么配置吗，我在react demo里加了个点击事件出现异常的时候，控制台并没有打印出来。
> ![demo-console](https://user-images.githubusercontent.com/17853356/129701848-1093a72a-040b-4f3c-a913-3f2b430ad338.png)

你init时，将maxBreadcrumbs设置成20 或者 30，我感觉是你的xhr太多把click给推出去了，我这边是可以收集到的
![image](https://user-images.githubusercontent.com/22608658/129703026-d00a71cf-1346-4b5e-a530-006282b014b1.png)

**Comment by C-somnus** [comment]
> > > > > > 你好，请问上报的接口中deviceInfo和record字段是有什么作用，我尝试的时候都是空对象和空数组
> > > > > 
> > > > > 
> > > > > deviceInfo是为了收集设备信息，比如当前网络类型、分辨率等等目前只有在小程序那块收集，record是收集页面录制的数据，当前没有对外开放SDK
> > > > 
> > > > 
> > > > 感谢答复，后续有开放计划吗。另外在问一下按钮点击事件记录UI.Click是不是没有对外开放
> > > 
> > > 
> > > UI.Click目前是有记录的，开源计划：目前正在优化前后端代码 ，后续会在 https://github.com/mitojs 这里面持续迭代的
> > 
> > 
> > UI.Click需要做什么配置吗，我在react demo里加了个点击事件出现异常的时候，控制台并没有打印出来。
> > ![demo-console](https://user-images.githubusercontent.com/17853356/129701848-1093a72a-040b-4f3c-a913-3f2b430ad338.png)
> 
> 你init时，将maxBreadcrumbs设置成20 或者 30，我感觉是你的xhr太多把click给推出去了，我这边是可以收集到的
> ![image](https://user-images.githubusercontent.com/22608658/129703026-d00a71cf-1346-4b5e-a530-006282b014b1.png)

刚好我是在chrome上用的div测试的，改成button就ok。
引用网上摘录
document.activeElement
document.activeElement三大浏览器(ie、firefox、chrome)都支持，但，针对的对象不同，返回的值也不同。
IE：
document.activeElement可获得所有聚焦的元素，包括input、textarea、div等。IE只关心光标聚焦的位置，不关心聚焦元素的性质。
chrome：
document.activeElement仅对input、textarea等标准的输入文本有效；对于div等非编辑类的元素(即使开启了contentEditable)，返回的值为BODY。
fireFox：
document.activeElement可获得所有聚焦的元素。包括input、textarea、div等。
