### ISSUE TITLE
服务端在哪里？不开源吗？

### ISSUE THREAD

**Issue by zhoubang85** [clouDr-f2e/monitor#49]
没有服务端的话，是不是现在还不能使用你这个项目做监控呢？

**Comment by Chryseis** [comment]
> 没有服务端的话，是不是现在还不能使用你这个项目做监控呢？

这个库是前端收集异常和性能的sdk，服务端部分的开源还在整理中，明年会单独开一个仓库进行开源

**Comment by youmengme** [comment]
2024年了 我还在等服务端和管理端前端 哈哈哈
